[package]
name = "lbclient"
version = "0.1.0"
edition = "2024"

[dependencies]
p256 = "0.13.2"
sqlite = "0.37.0"
rand_core = "0.6.4"
clap = { version = "4.5.41", features = ["derive"] }
termcolor = "1.4.1"
